/* automatically generated by rust-bindgen */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub const HAVE_ALLOCA: u32 = 1;
    pub const HAVE_MALLOC_H: u32 = 1;
    pub const HAVE_GETOPT_H: u32 = 1;
    pub const HAVE_GETOPT_LONG: u32 = 1;
    pub const HAVE_ISASCII: u32 = 1;
    pub const HAVE_ISWCTYPE: u32 = 1;
    pub const HAVE_ISWLOWER: u32 = 1;
    pub const HAVE_ISWUPPER: u32 = 1;
    pub const HAVE_MBRTOWC: u32 = 1;
    pub const HAVE_MBSTATE_T: u32 = 1;
    pub const HAVE_MBTOWC: u32 = 1;
    pub const HAVE_STDINT_H: u32 = 1;
    pub const HAVE_STDLIB_H: u32 = 1;
    pub const HAVE_STRINGS_H: u32 = 1;
    pub const HAVE_STRING_H: u32 = 1;
    pub const HAVE_SYS_STAT_H: u32 = 1;
    pub const HAVE_SYS_TYPES_H: u32 = 1;
    pub const HAVE_TOWUPPER: u32 = 1;
    pub const HAVE_WCHAR_H: u32 = 1;
    pub const HAVE_WCHAR_T: u32 = 1;
    pub const HAVE_WCSCHR: u32 = 1;
    pub const HAVE_WCSCPY: u32 = 1;
    pub const HAVE_WCSLEN: u32 = 1;
    pub const HAVE_WCSNCPY: u32 = 1;
    pub const HAVE_WCSRTOMBS: u32 = 1;
    pub const HAVE_WCTYPE: u32 = 1;
    pub const HAVE_WCTYPE_H: u32 = 1;
    pub const STDC_HEADERS: u32 = 1;
    pub const TRE_APPROX: u32 = 1;
    pub const WCHAR_T_UNSIGNED: u32 = 1;
    pub const _CRT_SECURE_NO_DEPRECATE: u32 = 1;
}
