/* automatically generated by rust-bindgen */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    
    
    pub const HAVE_ALLOCA: u32 = 1;
    pub const HAVE_ALLOCA_H: u32 = 1;
    pub const HAVE_SYS_TYPES_H: u32 = 1;
    pub const HAVE_WCHAR_H: u32 = 1;
    pub const TRE_APPROX: u32 = 1;
    pub const TRE_USE_ALLOCA: u32 = 1;
    pub const TRE_VERSION: &'static [u8; 14usize] = b"@TRE_VERSION@\0";
}
